Repository Leets-Official/Leets-BE, pull requests merged in 2025-02, with the labels that each got.

#49 feat: 이미지 에셋 추가
  src/main/resources/images/eatmateLogo.png
  src/main/resources/images/eatmateMain.png
  src/main/resources/images/gachitaxiLogo.png
  src/main/resources/images/gachitaxiMain.png
  src/main/resources/images/yesLogo.png
  src/main/resources/images/yesMain.png
Labels: 📄 docs

#52 fix: 활성 프로파일 변경
  Dockerfile
  src/main/java/land/leets/domain/mail/usecase/SendMailCron.java
Labels: 🐞 bug

#54 fix: 메일링 크론잡 변경
  src/main/java/land/leets/domain/mail/usecase/SendMailCron.java
Labels: ⚙️ setting

#56 fix: 메일링 크론잡 최종 변경
  src/main/java/land/leets/domain/mail/usecase/SendMailCron.java
Labels: ⚙️ setting

#58 feat: PM 직군 추가
  src/main/java/land/leets/domain/application/type/Position.java
Labels: ✨ feature
